### ISSUE TITLE
printTree not working

### ISSUE THREAD

**Issue by zausnerd** [zausnerd/pj1#1]
printTree() in BinarySearchTree.h is throwing compiler errors.

**Comment by aakside** [comment]
I see you tried to overload operator<< in the class, but it won't work the way you want.
http://stackoverflow.com/questions/9351166/does-overloading-operator-works-inside-the-class

Try this:
std::ostream& operator<<(std::ostream &out, const SequenceMap &a) {
    return out << a.getRecognitionSequence() << endl;
}

**Comment by zausnerd** [comment]
Solved!
